apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  # Base64 encoded values
  # DB_PASSWORD: "password123" -> cGFzc3dvcmQxMjM=
  # JWT_SECRET: "jwt-secret-key" -> and0LXNlY3JldC1rZXk=
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  JWT_SECRET: and0LXNlY3JldC1rZXk=